version: "3"
services:
  app:
    container_name: docker-node-machine
    restart: always
    build: .
    ports:
      - "80:8080"
    volumes:
      - "./src:/usr/src/app/src"
    links:
      - db:postgres
  db:
    container_name: "postgres"
    image: "postgres"
    restart: "always"
    ports:
      - "5342:5342"
    volumes:
      - "./db:/usr/src/app/db"
      - "./db/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: "erikandfiliprules987"
