version: "3"
services:
  app:
    container_name: docker-node-machine
    restart: always
    build: .
    ports:
      - "80:8080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "./src:/usr/src/app/src"
