version: "3"
services:
  app:
    container_name: docker-node-machine
    restart: always
    build: .
    ports:
      - "80:8080"
    volumes:
      - "./src:/usr/src/app/src"
    depends_on:
      - "db"
    environment:
      - DATABASE_URL=postgres://pumbapumba:erikandfiliprules987@db:5432/pumbadb
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 10; done; echo Waiting for database; npm start'
  db:
    container_name: "postgres"
    image: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "./db/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: "erikandfiliprules987"
      POSTGRES_DB: "pumbadb"
      POSTGRES_USER: "pumbapumba"
