# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      
     #   auth:
      #    username: $DOCKER_LOGIN
       #   password: $DOCKER_PWD

    working_directory: ~/repo
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      #- run: roliga tests kanske
      
      - setup_remote_docker:   
         docker_layer_caching: true 
         
     # - run:
      #   name: Install Docker client
       #  command: |
        #   set -x
         #  VER="18.05.0-ce"
         #  curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
         #  tar -xz -C /tmp -f /tmp/docker-$VER.tgz
         #  mv /tmp/docker/* /usr/bin
           
      - run:
          name: Docker Build
          command: |
            docker build -t mezzersmite/$BACK_END_IMAGE_NAME:$TAG .
            
      - run:
          name: Push to docker hub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push mezzersmite/$BACK_END_IMAGE_NAME:$TAG
            
      #- run:
      #   name: Deploy to Azure back-end VM
          #echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          

#comment
