-- This document is made to structure and fill up the database with content.
-- Have hashed passwords with a salt.
-- https://stackoverflow.com/questions/2647158/how-can-i-hash-passwords-in-postgresql
CREATE TYPE PF AS ENUM ('instagram', 'twitter', 'youtube');

CREATE TYPE SEXX AS ENUM ('Male','Female');

--- User table. Containing info about user
CREATE TABLE USR (
  USRID SERIAL PRIMARY KEY,
  USRNAME VARCHAR(20) NOT NULL UNIQUE,
  HASHEDPWD VARCHAR NOT NULL,
  EMAIL VARCHAR UNIQUE,
  AGE INT,
  SEX SEXX -- Can be "Male" or "Female"
);

-- Specifies Location table, used to
CREATE TABLE LOCATION (
  LOCATIONID SERIAL PRIMARY KEY,
  LOCATIONNAME VARCHAR NOT NULL,
  LOCATIONTYPE VARCHAR NOT NULL,
  REGIONID INTEGER REFERENCES LOCATION(LOCATIONID) DEFAULT NULL,
  COUNTRYID INTEGER REFERENCES LOCATION(LOCATIONID) DEFAULT NULL
);

--
CREATE TABLE INFLUENCER (
  INFLUENCERID SERIAL PRIMARY KEY, -- ID for the influencer in OUR database
  INFLUENCERNAME VARCHAR NOT NULL UNIQUE, -- The name of the influencer, e.g., Pewdiepie
  REALNAME VARCHAR, -- The real name, for example pewdiepie = Felix Kjellberg. For a lot of influencers, this is the same for all.
  AGE INT, -- How old the influencer is
  SEX SEXX, -- Enum type. Can be 'Male' or 'Female' (case-sensitive)
  PICTURELINK TEXT, -- Link for a profile picture
  COUNTRYID INTEGER REFERENCES LOCATION(LOCATIONID) DEFAULT NULL, -- Which country the influencer lives in
  CITYID INTEGER REFERENCES LOCATION(LOCATIONID) DEFAULT NULL -- Which city the influencer lives in
);

CREATE TABLE USRFLWINFL (
  RELATIONID SERIAL PRIMARY KEY, -- Just an id. Not really useful or important atm.
  FLWRID INTEGER REFERENCES USR (USRID) NOT NULL, -- The id of the user following an influencer
  INFLID INTEGER REFERENCES INFLUENCER(INFLUENCERID) NOT NULL -- The id of the influencer a user follows.
);
ALTER TABLE USRFLWINFL -- constraint added to make sure that only one follow exists.
ADD CONSTRAINT UNIQUEFLWRELATION
UNIQUE (FLWRID,INFLID);

CREATE TYPE VISITTYPE AS ENUM ('profilevisit', 'instagrampost', 'twitterpost', 'youtubevideo');

-- Have this table to track the number of visits?
CREATE TABLE USRVISIT ( -- Table that describes a visit to a profile
  RELATIONID SERIAL PRIMARY KEY, -- ID
  USRID INTEGER REFERENCES USR (USRID) NOT NULL,
  INFLID INTEGER REFERENCES INFLUENCER(INFLUENCERID) NOT NULL,
  VISITTIME TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- 
  TYPEOFVISIT VISITTYPE NOT NULL -- Type of visit. Did they see a post from a platform, or visit the user's profile?
);

CREATE TABLE POST (
  POSTID SERIAL PRIMARY KEY,
  INFLID INTEGER REFERENCES INFLUENCER(INFLUENCERID) NOT NULL,
  NRLIKES INT NOT NULL,
  PLATFORM PF NOT NULL,
  USRTXTCONTENT TEXT,
  POSTED TIMESTAMPTZ,
  POSTPLATFORMID INTEGER, -- The specific id on the platform for the post
  POSTURL VARCHAR UNIQUE, -- The url for the post
  PLATFORMCONTENT JSON --TODO: decide whether JSONB or JSON is best. JSONB supports indexing, is faster to process but slower to insert.
);

ALTER TABLE POST -- constraint forcing us to store only one of each post. Uses the platform and the id on that platform to make it unique
ADD CONSTRAINT UNIQUEPLATFORMPOSTID
UNIQUE (POSTPLATFORMID,PLATFORM);

CREATE TABLE USRLIKEPOST (
  USRLIKE SERIAL PRIMARY KEY,
  POSTID INTEGER REFERENCES POST(POSTID),
  USRID INTEGER REFERENCES USR(USRID)
);
ALTER TABLE USRLIKEPOST
ADD CONSTRAINT UNIQUELIKE
UNIQUE (POSTID,USRID);

CREATE TABLE TAG (
  TAGID SERIAL PRIMARY KEY,
  TAGNAME VARCHAR,
  POSTID INTEGER REFERENCES POST (POSTID) DEFAULT NULL,
  INFLID INTEGER REFERENCES INFLUENCER (INFLUENCERID) DEFAULT NULL
);


CREATE TABLE PLATFORMACCOUNT (
  INFLID INTEGER REFERENCES INFLUENCER (INFLUENCERID) NOT NULL,
  -- TODO: WHAT IS THE MAX AMT OF CHARS IN THE NAME
  ACTNAME VARCHAR NOT NULL,
  -- MIGHT HAVE TO BE MODIFIED IF WE INTRODUCE MORE PLATFORMS
  PLATFORM PF NOT NULL,
  NRFLWRS INT, -- IS SUBSCRIBERS FOR YOUTUBE
  MEMBERSINCE DATE,
  ACTURL TEXT,
  VERIFIED BOOLEAN,
  USRDESC TEXT,
  PLATFORMCONTENT JSON
);

ALTER TABLE PLATFORMACCOUNT
ADD CONSTRAINT UNIQUEPLATFORMACT
UNIQUE (ACTNAME,PLATFORM);

CREATE TABLE TVOPERATOR (
  TVOPERATORID SERIAL PRIMARY KEY,
  TVOPERATORNAME VARCHAR NOT NULL,
  HASHEDPWD VARCHAR NOT NULL
);

CREATE TABLE PROMOTION (
  PROMOTIONID SERIAL PRIMARY KEY,
  TVOPERATORID INTEGER REFERENCES TVOPERATOR(TVOPERATORID) NOT NULL,
  STARTDATE TIMESTAMPTZ,
  ENDDATE TIMESTAMPTZ
);

CREATE TABLE TAGFORINFLUENCER (
  TAGID INTEGER REFERENCES TAG(TAGID),
  INFLID INTEGER REFERENCES INFLUENCER(INFLUENCERID)
);

CREATE TABLE TAGFORPOST (
  TAGID INTEGER REFERENCES TAG(TAGID) NOT NULL,
  POSTID INTEGER REFERENCES POST(POSTID)
);

CREATE TABLE TAGPROMOTED (
  TAGID INTEGER REFERENCES TAG(TAGID) NOT NULL,
  PROMOTIONID INTEGER REFERENCES PROMOTION(PROMOTIONID) NOT NULL,
  ISPROMOTION BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE INFLUENCERPROMOTED (
  INFLUENCERID INTEGER REFERENCES INFLUENCER(INFLUENCERID) NOT NULL,
  PROMOTIONID INTEGER REFERENCES PROMOTION(PROMOTIONID) NOT NULL,
  ISPROMOTION BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE LOCATIONPROMOTED (
  LOCATIONID INTEGER REFERENCES LOCATION(LOCATIONID) NOT NULL,
  PROMOTIONID INTEGER REFERENCES PROMOTION(PROMOTIONID) NOT NULL
);
