--CREATE TABLE INFLUENCER (
--  INFLUENCERID INT PRIMARY KEY NOT NULL,
--  INFLUENCERNAME VARCHAR(30) NOT NULL,
--  REALNAME VARCHAR(30),
--  AGE INT,
--  COUNTRYID INT REFERENCES LOCATION(LOCATIONID),
--  CITYID INT REFERENCES LOCATION(LOCATIONID)
--);


INSERT INTO LOCATION (LOCATIONNAME) VALUES ("Sweden")
INSERT INTO LOCATION (LOCATIONNAME) VALUES ("United States")
INSERT INTO INFLUENCER (INFLUENCERNAME, REALNAME, AGE) VALUES ('Bill Gates', 'Bill Gates', 62);
