-- This document is made to structure and fill up the database with content.
-- Have hashed passwords with a salt.
-- https://stackoverflow.com/questions/2647158/how-can-i-hash-passwords-in-postgresql
CREATE TABLE USR (
  USRID INT PRIMARY KEY NOT NULL,
  USRNAME VARCHAR(20) NOT NULL UNIQUE,
  HASHEDPWD VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(20),
  AGE INT,
  SEX BOOLEAN -- 1 for male, 0 for female
);

CREATE TABLE LOCATION (
  LOCATIONID INT PRIMARY KEY NOT NULL,
  LOCATIONNAME VARCHAR NOT NULL,
  REGIONID INT REFERENCES LOCATION(LOCATIONID)
);

CREATE TABLE INFLUENCER (
  INFLUENCERID INT PRIMARY KEY NOT NULL,
  INFLUENCERNAME VARCHAR(30) NOT NULL,
  REALNAME VARCHAR(30),
  AGE INT,
  COUNTRYID INT REFERENCES LOCATION(LOCATIONID),
  CITYID INT REFERENCES LOCATION(LOCATIONID)
);

CREATE TABLE USRFLWINFL (
  RELATIONID INT PRIMARY KEY NOT NULL,
  FLWRID INT REFERENCES USR (USRID) NOT NULL,
  INFLID INT REFERENCES INFLUENCER(INFLUENCERID) NOT NULL
);

-- Have this table to track the number of visits?
CREATE TABLE USRVISIT (
  RELATIONID INT PRIMARY KEY NOT NULL,
  USRID INT REFERENCES USR (USRID) NOT NULL,
  INFLID INT REFERENCES INFLUENCER(INFLUENCERID) NOT NULL,
  VISITTIME TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  VISITTYPE VARCHAR NOT NULL
);

CREATE TABLE POST (
  POSTID INT PRIMARY KEY NOT NULL,
  INFLID INT REFERENCES INFLUENCER(INFLUENCERID) NOT NULL,
  NRLIKES INT NOT NULL,
  PLATFORM VARCHAR(9) NOT NULL,
  USRTXTCONTENT TEXT,
  POSTED TIMESTAMPTZ,
  POSTURL VARCHAR, --EXACTLY THE SAME AS
  PLATFORMCONTENT JSON --TODO: decide whether JSONB or JSON is best. JSONB supports indexing, is faster to process but slower to insert.
);

CREATE TABLE TAG (
  TAGID INT PRIMARY KEY NOT NULL,
  TAGNAME VARCHAR,
  POSTID INT REFERENCES POST (POSTID),
  INFLID INT REFERENCES INFLUENCER (INFLUENCERID) NOT NULL
);

CREATE TABLE PLATFORMACCOUNT (
  INFLID INT REFERENCES INFLUENCER (INFLUENCERID) NOT NULL,
  -- TODO: WHAT IS THE MAX AMT OF CHARS IN THE NAME
  ACTNAME VARCHAR(30) NOT NULL,
  -- MIGHT HAVE TO BE MODIFIED IF WE INTRODUCE MORE PLATFORMS
  PLATFORM VARCHAR(9) NOT NULL,
  NRFLWRS INT NOT NULL, -- IS SUBSCRIBERS FOR YOUTUBE
  MEMBERSINCE DATE,
  ACTURL TEXT NOT NULL,
  VERIFIED BOOLEAN,
  USRDESC TEXT,
  PLATFORMCONTENT JSON
);

CREATE TABLE TVOPERATOR (
  TVOPERATORID INT PRIMARY KEY NOT NULL,
  TVOPERATORNAME VARCHAR NOT NULL,
  HASHEDPWD VARCHAR NOT NULL
);

CREATE TABLE PROMOTION (
  PROMOTIONID INT PRIMARY KEY NOT NULL,
  TVOPERATORID INT REFERENCES TVOPERATOR(TVOPERATORID) NOT NULL,
  STARTDATE TIMESTAMPTZ,
  ENDDATE TIMESTAMPTZ
);

CREATE TABLE TAGPROMOTED (
  TAGID INT REFERENCES TAG(TAGID) NOT NULL,
  PROMOTIONID INT REFERENCES PROMOTION(PROMOTIONID) NOT NULL,
  ISPROMOTION BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE INFLUENCERPROMOTED (
  INFLUENCERID INT REFERENCES INFLUENCER(INFLUENCERID) NOT NULL,
  PROMOTIONID INT REFERENCES PROMOTION(PROMOTIONID) NOT NULL,
  ISPROMOTION BOOLEAN NOT NULL DEFAULT TRUE
);
