INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Gary Vaynerchuck');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Joe Rogan');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Kylie Jenner');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Martin Larsson');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Kenza');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Margaux Dietz');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Isabella Jedler');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Jon Olsson');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Janni Olsson Delér');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Anna Nyström');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Felix Kjellberg');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Marzia Bisognin');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Dalai Lama');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Marques Brownlee');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Lewis Hilsenteger');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Mark Hamill');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Justine Ezarik');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Casey Neistat');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Pope Francis');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Gordon Ramsay');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Jimmy Chin');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Justin Bieber');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Donald Trump');
INSERT INTO INFLUENCER (INFLUENCERNAME) VALUES ('Barack Obama');



-- Insert Twitter accounts
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Gary Vaynerchuck'),'Garyvee','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Joe Rogan'),'Joerogan','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Kylie Jenner'),'KylieJenner','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Martin Larsson'),'RekklesLoL','twitter');



INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Bill Gates'),'BillGates','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Jon Olsson'),'JonOlsson','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Janni Olsson Delér'),'JanniDeler','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Anna Nyström'),'AnnaNystromT','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Felix Kjellberg'),'pewdiepie','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Marzia Bisognin'),'marziapie','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Dalai Lama'),'DalaiLama','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Marques Brownlee'),'MKBHD','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Lewis Hilsenteger'),'UnboxTherapy','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Mark Hamill'),'HamillHimself','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Justine Ezarik'),'ijustine','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Casey Neistat'),'CaseyNeistat','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Pope Francis'),'Pontifex','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Gordon Ramsay'),'gordonramsay','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Jimmy Chin'),'jimkchin','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Justin Bieber'),'justinbieber','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Donald Trump'),'realDonaldTrump','twitter');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Barack Obama'),'BarackObama','twitter');

-- Insert instagram accounts
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Gary Vaynerchuck'),'Garyvee','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Joe Rogan'),'Joerogan','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Kylie Jenner'),'kyliejenner','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Martin Larsson'),'fnaticrekkleslol','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Kenza'),'Kenzas','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Margaux Dietz'),'Margauxdietz','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Isabella Jedler'),'isabellajedler','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Bill Gates'),'thisisbillgates','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Jon Olsson'),'jonolsson1','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Janni Olsson Delér'),'jannid','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Anna Nyström'),'annanystrom','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Felix Kjellberg'),'pewdiepie','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Marzia Bisognin'),'itsmarziapie','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Dalai Lama'),'dalailama','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Marques Brownlee'),'mkbhd','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Lewis Hilsenteger'),'unboxtherapy','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Mark Hamill'),'hamillhimself','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Justine Ezarik'),'ijustine','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Casey Neistat'),'CaseyNeistat','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Pope Francis'),'franciscus','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Gordon Ramsay'),'gordongram','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Jimmy Chin'),'jimmy_chin','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Justin Bieber'),'justinbieber','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Donald Trump'),'realDonaldTrump','instagram');
INSERT INTO PLATFORMACCOUNT (INFLID, ACTNAME, PLATFORM) VALUES ((SELECT INFLUENCERID FROM INFLUENCER WHERE INFLUENCERNAME = 'Barack Obama'),'barackobama','instagram');
